// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VectorPlus.Web.Service.Db;

namespace VectorPlus.Web.Migrations
{
    [DbContext(typeof(VectorPlusBackgroundServiceDbContext))]
    [Migration("20200509201201_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("VectorPlus.Web.Service.Db.ModuleConfig", b =>
                {
                    b.Property<Guid>("ModuleConfigId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Added")
                        .HasColumnType("TEXT");

                    b.Property<string>("Author")
                        .HasColumnType("TEXT");

                    b.Property<string>("AuthorEmail")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("DLL")
                        .HasColumnType("BLOB");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModuleWebsite")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Release")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UserEnabled")
                        .HasColumnType("INTEGER");

                    b.HasKey("ModuleConfigId");

                    b.ToTable("Modules");
                });
#pragma warning restore 612, 618
        }
    }
}
